### ISSUE TITLE
"Mutable" no longer being used

### ISSUE THREAD

**Issue by sarina** [openedx/XBlock#140]
In [fields.py](https://github.com/openedx/XBlock/blob/master/xblock/fields.py#L310) class `Field` we have a property `MUTABLE` which was originally created for bulk save logic.

My understanding is that this property is no longer being used with @cpennington's changes to XBlock save logic. If this is the case, we should strip out all references to `MUTABLE` within XBlock.

Thanks @dmitchell for noting this.

**Acceptance Criteria:**

- [ ] Make sure `MUTABLE` is no longer used.
- [ ] Strip out all references to `MUTABLE` within XBlock.
- [ ] Install the Xblock as a package on some customized Xblock and make sure everything is working fine

**Comment by farhan** [comment]
@sarina @cpennington It would be great if you could add the PR link related to the `XBlock save logic` change. It will help to understand the ticket in detail.
cc: @feanil

**Comment by feanil** [comment]
Looking at the code, it looks like the `MUTABLE` property is indeed never referenced for decision making within the xblock repo.  @farhan to complete this work.  Make sure the `MUTABLE` property is not being referenced by any runtimes in `edx-platform` and if that is the case, we should be able to remove the property and release a new version of this repo.

**Comment by salman2013** [comment]
@feanil  I did not find `MUTABLE` property referenced by any runtime in `edx-platform`.  
There is a [condition](https://github.com/openedx/XBlock/blob/24f7f3de98557ec4c3c3f6428824230ef838237f/xblock/fields.py#L337) in XBlock but i am not sure if should we remove it.

**Comment by feanil** [comment]
I think given that it is not actually set anywhere, we can just remove it and choose the default branch of any conditionals.

**Comment by salman2013** [comment]
@feanil I have created PR for it. https://github.com/openedx/XBlock/pull/727

**Comment by salman2013** [comment]
After discussion on the [PR](https://github.com/openedx/XBlock/pull/727) of this ticket, We found that there might be a memory usage implication for this change. It may produce more copies of the defaults than we want for certain objects. We decided to keep this code as it is and close this issue.
