### ISSUE TITLE
Switch off of deprecated `pkg_resources` library

### ISSUE THREAD

**Issue by kdmccormick** [openedx/XBlock#641]
### Background

The `pkg_resources` library, used by XBlock to load static assets, [is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html). The [removal timeline is unknown](https://github.com/pypa/setuptools/discussions/3934).

XBlock uses `pkg_resources` in a couple places.

XBlock also recommend `pkg_resources` in its docs: https://edx.readthedocs.io/projects/xblock-tutorial/en/latest/anatomy/python.html

### To do

First, choose a new resource loading interface. Options:

* Use [`importlib.resources`](https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources). Unfortunately, this will become deprecated in Python 3.11 and replaced with a yet-to-be-determined interface.
* Wait until Python 3.11, and then switch to the 3.11 replacement.
* [Merge xblock-utils into this repository](https://github.com/openedx/XBlock/issues/675). That library provides a `ResourceLoader` abstraction; adopt that.

Then:

* Update the docs to recommend the new interface.
* Update any uses of `pkg_resources` in this repo.
* Reach out to XBlock maintainers (including maintainers of edx-platform, which defines several XBlocks!) to request that they switch from pkg_resources to the new interface.

### Related

* https://github.com/openedx/XBlock/issues/675
* https://github.com/openedx/XBlock/issues/676

**Comment by farhan** [comment]
Its a duplicate story of following
https://github.com/openedx/XBlock/issues/676
