### ISSUE TITLE
Switch off of deprecated `pkg_resources` library

### ISSUE THREAD

**Issue by kdmccormick** [openedx/XBlock#676]
### Background

The `pkg_resources` library, used by XBlock to load static assets, [is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html). The [removal timeline is unknown](https://github.com/pypa/setuptools/discussions/3934).

xblock-utils uses `pkg_resources` in a couple places.

### To do

First, choose a new resource loading interface. Options:

* Use [`importlib.resources`](https://docs.python.org/3.8/library/importlib.html?highlight=importlib#module-importlib.resources). Unfortunately, this will become deprecated in Python 3.11 and replaced with a yet-to-be-determined interface.
* Wait until Python 3.11, and then switch to the 3.11 replacement.

Then:

* Update the code in xblock-utils.

### Related

* https://github.com/openedx/XBlock/issues/641
* https://github.com/openedx/XBlock/issues/675

**Comment by farhan** [comment]
After reading the related docs/blogs shared below I think we should choose [importlib_resources](https://pypi.org/project/importlib-resources/) library which is developed and maintained by Python developers and fixes the architecture issues related to [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources) module which is going to deprecated in Python 3.11 as discussed [here](https://discuss.python.org/t/deprecating-importlib-resources-legacy-api/11386)

Docs/Blogs
https://discuss.python.org/t/deprecating-importlib-resources-legacy-api/11386
https://importlib-resources.readthedocs.io/en/latest/using.html
https://docs.python.org/3/library/importlib.resources.html
https://www.geeksforgeeks.org/importlib-package-in-python/
https://dev.to/bowmanjd/easily-load-non-python-data-files-from-a-python-package-2e8g

FYI @kdmccormick @feanil

**Comment by kdmccormick** [comment]
@farhan , thanks for the research. I took a look at the Python forum post and came to the conclusion that:

* `pkg_resources` is what we use now. It is deprecated but will still work in Python 3.11.
* `importlib.resources` was introduced in Python 3.7, but its API had design problems.
* `importlib_resources` is a better, redesigned version of that API.
* In Python 3.11, `importlib_resources` becomes official, as `importlib.resources`, thus deprecating the old, problematic version of the API.

So, it sounds like we could wait until edx-platform is upgraded to Python 3.11, and then just switch directly to the new, official `importlib.resources` package. Does that sound good?

**Comment by feanil** [comment]
As an additional note, it looks like pkg_resources is still around in 3.12 so it will be safe to jump to that as well so I think we can de-prioritize this until after the python upgrade which we'll hopefully kick-off soon.

**Comment by farhan** [comment]
PR is blocked as we are waiting for drop of Python `v3.8` support from edx-platform
