### ISSUE TITLE
manage.py

### ISSUE THREAD

**Issue by ghost** [openedx/XBlock#9]
When I run step 4: 
python manage.py runserver

I got the following message:
can't open file 'manage.py': [Errno 2] No such file or directory

I have tried many things, but I still do not get it working.

**Comment by abhishekbit** [comment]
wen i create a new project using "django-admin.py startproject project_name",it doesnt create any manage.py file.rest all necessary files are created.
plzz help asap.

**Comment by nedbat** [comment]
@abhishekbit The edx-code mailing list is the right place to get help: https://groups.google.com/forum/#!forum/edx-code
